### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by magnetik** [EXSyst/ApiDocBundle#1]
Heyo,

Just tried out the bundle and it's already really promising. 

Had a little problem with the RouterDescriber

    if ($method = $this->getReflectionMethod($route->getDefault('_controller'))) {

`$route->getDefault('_controller')` returns null for the `/logout` route in my project where API and website is mixed.

Another consequence of my web + api project is that I would like to filter to have only routes that are in some specific controllers or specific routes (something like all routes that starts with `/api`). 

Would you like some pull request to implement some things here? 
A list of things to be done would be cool 

Thanks

**Comment by GuilhemN** [comment]
Thanks for the feedback !

>Had a little problem with the RouterDescriber

I'll fix it this afternoon :)

> Another consequence of my web + api project is that I would like to filter to have only routes that are in some specific controllers or specific routes (something like all routes that starts with /api).

That would be cool indeed, it should be done using configuration imo :)

I've made [a small list](https://github.com/EXSyst/ApiDocBundle#whats-next) of the most important stuff to implement that we can extend if you have other ideas.

**Comment by GuilhemN** [comment]
> Had a little problem with the RouterDescriber

Actually, errors should [be ignored](https://github.com/EXSyst/ApiDocBundle/blob/master/Describer/RouteDescriber.php#L109). What was the problem exactly?

**Comment by magnetik** [comment]
`$route->getDefault('_controller')` return null, and is used as argument of `getReflectionMethod(string $controller)` that does not allow it

**Comment by GuilhemN** [comment]
Indeed, I didn't think about this possibility... Thanks, https://github.com/EXSyst/ApiDocBundle/commit/f6f91562d9e7ac0edb4e892969dea1ed30c931af fixes it !
