### ISSUE TITLE
Conflict between symfony path parameter and swagger specification

### ISSUE THREAD

**Issue by magnetik** [EXSyst/ApiDocBundle#3]
Using FOSRestBundle, all routes have the path defined as `"/foo/bar.{_format}"`

The `_format` has a default value, but open api specification state: 

    required: If the parameter is in "path", this property is required and its value MUST be true.
    default: (Note: "default" has no meaning for required parameters.)

**Comment by GuilhemN** [comment]
The only "solution" I found is [removing `.{_format}`](https://github.com/EXSyst/ApiDocBundle/blob/master/RouteDescriber/RouteDescriberTrait.php#L44-L50). Maybe we should ask if this limitation can be removed in the next version of the specification.

**Comment by magnetik** [comment]
Well for me the fix does not work: even with the `{._format}` removed from path, the `RouteMetadataDescriber` gets it from the compiled route and it's added.

**Comment by GuilhemN** [comment]
Is https://github.com/EXSyst/ApiDocBundle/pull/5 fine for you or do you see another solution?

**Comment by GuilhemN** [comment]
Fixed in #5 :)
